// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package edu.aspire.bookstore.service;


public class Catalog_getBookPrice_ResponseStruct {
    protected float result;
    
    public Catalog_getBookPrice_ResponseStruct() {
    }
    
    public Catalog_getBookPrice_ResponseStruct(float result) {
        this.result = result;
    }
    
    public float getResult() {
        return result;
    }
    
    public void setResult(float result) {
        this.result = result;
    }
}
