// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package edu.aspire.bookstore.service;


public class Catalog_getBookPrice_RequestStruct {
    protected java.lang.String String_1;
    
    public Catalog_getBookPrice_RequestStruct() {
    }
    
    public Catalog_getBookPrice_RequestStruct(java.lang.String String_1) {
        this.String_1 = String_1;
    }
    
    public java.lang.String getString_1() {
        return String_1;
    }
    
    public void setString_1(java.lang.String String_1) {
        this.String_1 = String_1;
    }
}
